# The URL the site will be built for
base_url = "https://particle.vercel.app"

title = "Jack's blog"
description = "A blog about lorem ipsum dolor sit amet"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "Jack's Den"
user_description = "Code, Sculpting, Game Design, and everything inbetween"
user_title = "Coding Creative"
email = "anon@anon.com"
twitter_username = "lorem_ipsum"
github_username =  "thelazyone"
gplus_username =  "lorem_ipsum"

# Google-analytics
google_analytics.id = ""
